### ISSUE TITLE
ucontext is deprecated on OSX

### ISSUE THREAD

**Issue by pragdave** [bakkdoor/fancy#13]
The following patch seems to allow Fancy to build on 10.6: 

https://gist.github.com/6b96645fea287397819c

**Comment by bakkdoor** [comment]
Thanks! Will apply the patch :)

**Comment by bakkdoor** [comment]
vendor/gc/mach_dep.c: Applied libgc patch by pragdave for letting it build nice on Mac OSX 10.6 Closed by 36d008a99300b6ceff1e7b0cc003d5f7b023de05
