### ISSUE TITLE
Better error-messages

### ISSUE THREAD

**Issue by NilsHaldenwang** [bakkdoor/fancy#17]
Would be very nice to get the file and line where the error occured.

**Comment by bakkdoor** [comment]
this should already be the case. i think the wrong line numbers etc. result in using String#eval which messes up that logic. will look into it. shouldn't be too hard to fix.

**Comment by vic** [comment]
Works now on bootstrap branch, as we use rubinius backtraces. One issue though.. the filename for error reporting is shown as "foo.fyc" instead of "foo.fy" even though the line is correct. Need to fix it in the compiler chain, so the filename given to the generated compiled method ends with ".fy"

**Comment by bakkdoor** [comment]
Fix to Fancy::CodeLoader#load_compiled_file() to use the actual .fy filename in backtraces instead of the compiled filename (e.g. lib/object.fy:123 instead of lib/object.fyc:123). Closed by ab2d302db2d1613fe66164f53aad5c2a46ff1318
