### ISSUE TITLE
Building error on OS X 10.6.4

### ISSUE THREAD

**Issue by goyox86** [bakkdoor/fancy#22]
I'm getting this when i try to compile the changes in fb60a548:

method_definition.cc: In member function ‘virtual fancy::FancyObject\* fancy::parser::nodes::ClassConstructorMethod::call(fancy::FancyObject_, fancy::Scope_, fancy::FancyObject_)’:
method_definition.cc:30: error: ISO C++ forbids zero-size array ‘args’
make[3]: *_\* [method_definition.o] Error 1
make[2]: **\* [subdirs] Error 2
/bin/sh: line 0: cd: bootstrap: No such file or directory
make[1]: **\* [subdirs] Error 1
make: **\* [fancy] Error 2

This is the output from "gcc --version":

i686-apple-darwin10-gcc-4.2.1 (GCC) 4.2.1 (Apple Inc. build 5664)
Copyright (C) 2007 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by bakkdoor** [comment]
Ah ok i got that warning as well but it compiled ok. Will change it. Thanks!

**Comment by bakkdoor** [comment]
I have gcc (Ubuntu 4.4.3-4ubuntu5) 4.4.3
Looks like older versions fail to build with it, while the newer version just displays it as a warning. Anyway, will change it since I don't like warnings anyway :)

**Comment by bakkdoor** [comment]
Pass in nil instead of empty array into ClassConstructorMethod::call(). This closed by 1984de9ea4aad000e5129c76a6e3357777370859
