### ISSUE TITLE
Add a pygments lexer for Fancy

### ISSUE THREAD

**Issue by bakkdoor** [bakkdoor/fancy#25]
So we can have syntax highlighting here on GitHub ;)

See: http://pygments.org/docs/lexerdevelopment/

**Comment by goyox86** [comment]
This one is mine!, Should i write the lexer, and give it to bakkdoor?

**Comment by bakkdoor** [comment]
Write it and put it in a repository in the fancy-lang organization. i'll create the repo, you can just push to it =)

**Comment by bakkdoor** [comment]
See: https://github.com/fancy-lang/fancy-pygments

**Comment by bakkdoor** [comment]
Done. At least mostly. See: https://github.com/fancy-lang/fancy-pygments
