### ISSUE TITLE
Create fancy book.

### ISSUE THREAD

**Issue by vic** [bakkdoor/fancy#28]
Create a fancy doc  command, something like rubinius is doing to document their project. 

We could aso create another repository for an opensource "Programming Fancy" like book. To teach from the basics, just like ruby's pick-axe.... name proposal for the book: "Programming In-Fancy"

If _why is found (that means.. the inner _why inside ourselves) he might want to create a "try fancy" or _why's pogniant guide to fancy!

**Comment by bakkdoor** [comment]
Good idea. We probably can use markdown to generate the html etc.

**Comment by bakkdoor** [comment]
In the works. Will close this for now.
