### ISSUE TITLE
Expression in catch condition.

### ISSUE THREAD

**Issue by vic** [bakkdoor/fancy#29]
try {
   foo
} catch <<Expression>> => e {
   bar
}

Currently, the fancy parser expects only an identifier in place of <<Expression>>. We need that to be any fancy object. (say an array, or tipically a class identifier, but at runtime, anything that responds to ===)

**Comment by bakkdoor** [comment]
ok makes sense. will add that to the parser.

**Comment by vic** [comment]
implemented in bootstrap parser.
