### ISSUE TITLE
String interpolation.

### ISSUE THREAD

**Issue by vic** [bakkdoor/fancy#30]
Make the parser and compiler support interpolating expressions in strings. 

 "Some #{expression} String"

I propose the #{} syntax for ruby compat.

**Comment by bakkdoor** [comment]
Yeah, initially wanted that for fancy all along, but couldn't get the parser to deal with it :P
I know, I'm impatient...

**Comment by bakkdoor** [comment]
Yo, this is kinda done. Still room for improvement. Especially, as you can't use literal strings in them yet (need to fix the lexer, but i hate doing that so i will defer it :P). See: https://github.com/bakkdoor/fancy/commit/591a0b0c9e6311457d3397b7a44a59973e6b31ae
