### ISSUE TITLE
Splat arguments for ruby_args.

### ISSUE THREAD

**Issue by vic** [bakkdoor/fancy#31]
Now we support the new syntax for calling ruby methods:

```
  some object method(foo, bar, &block)
```

Add support for *identifier on it 

```
  some object method(*something, &block)
```

Note: currently, the compiler doesn't accept arbitrary expressions following & like in ruby, what we actually do is having a fancy identifier starting with &, and if found as last argument, the variable (without &) is pushed and given as block to the call. This, IMHO is fine for fancy, otherwise we may complicate the parser a lot. So for splat arguments we could do the same thing, take an identifier and just push its flatten value as if they were arguments.

**Comment by bakkdoor** [comment]
Sounds reasonable. I think we should do it that way for now.

**Comment by bakkdoor** [comment]
Done.
