### ISSUE TITLE
Ruby send without explicit parens for ruby methods taking more than one arg.

### ISSUE THREAD

**Issue by vic** [bakkdoor/fancy#32]
You may have noticed currently we can do the following in fancy:

```
 object method()
```

To invoke a ruby method without arguments on object. 

When we want to invoke a ruby method (like each) that takes no arguments, but a single block
we can do this (and it actually works now):

```
 object each |item| { item println }
```

That is, giving a block literal after the method identifier. That's fine because it's unambiguous with the syntax for calling fancy methods (fancy methods use selectors ending with ":" like in smalltalk).

Now.. the point of this issue (feel free to comment, Im not very fond of it, but would like to know what you think):

We could modify the parser to recognize the following as a ruby_send ...

```
   object method foo, bar, baz
```

If you notice, we have:

```
  <receiver> <identifier> <expr2_comma_list>
```

where expr2_comma_list has at least two expressions (and hence at least one comma)

the advantage would be that it would be more familiar for ruby people (as in ruby most of the time you can omit parens). 
The downside is this would work only for ruby methods taking more than one argument (so we could have at least one "," in expr2_comma_list)

What you think?

**Comment by bakkdoor** [comment]
Hmm..I think we should stick with the explicit version with parentheses for now. It seems more clear and every ruby programmer will know what's going on just fine. I'm not very fond of having too many ways to express things syntax-wise. Also, in cases of methods with just one argument, we'd need them anyway so there's just too much complication imho. Maybe we should keep this ticket around in case more people favor it in the future?

**Comment by bakkdoor** [comment]
Closed for now. If more discussion on this is wanted, we can always reopen it.
