### ISSUE TITLE
Gemfile for Fancy

### ISSUE THREAD

**Issue by vic** [bakkdoor/fancy#35]
Now that Fancy runs on Rubinius VM. We could distribute a rubygem for that platform. 
That might increase the number of users.

**Comment by bakkdoor** [comment]
Sure, makes sense. Want to work on it or should I do it?

**Comment by vic** [comment]
Please do it.

BTW, you might want to also update the debian package, as it's no longer built the same way.

**Comment by bakkdoor** [comment]
Yeah, you're right. Will also do that when I have time.

**Comment by bakkdoor** [comment]
Done.
