### ISSUE TITLE
Pattern matching - Method dispatch.

### ISSUE THREAD

**Issue by vic** [bakkdoor/fancy#37]
Being erlang one of fancy's inspirations, I'd like to add support for pattern matching to method dispatch. Something similar to what we can find in functional languages like haskell,  So here's my proposal..

```
# Proposal for pattern matching dispatch in fancy.
#
# The syntax is as follows:
#  Any argument identifier can be followed of
#    ( pattern )
#  Where pattern can be one of the following:
#
#    expr
#    expr | expr
#    expr , expr
#
#  The resulting pattern object will be compared
#  using the === operator with the actual given argument
#  If this comparission results true, the method
#  is invoked.

# Using an object as pattern
def fact: n (0) { 1 }
def fact: n (1) { 1 }
# Using a block as pattern.
def fact: n ({ n > 1 }) { n + fact: n - 1 }


# Let's rewrite this...


# The pattern
#   a | b
# Matches if any of the alternatives does.
def fact: n (0 | 1) { 1 }

# The pattern
#   a , b
# Matches if all of the patterns do.
# This example illustrates this and using a block to
# test if the method should be invoked. Note
# the variable is bound on the block body.
def fact: n (Number, { n > 1 }) { n + fact: n - 1 }

# Fallback to anything, just like normal fancy
def fact: x { "Invalid value for factorial" raise! }
```

This would work fine with "optional args" I'm implementing 

```
# A method that only prints strings, defaults to "hello"
def foo: x (String) = "hello" { x println } 
```

**Comment by bakkdoor** [comment]
Hmm.. So for methods with multiple patterns, how would that look like? Especially for methods with more than one argument?

**Comment by vic** [comment]
```
def foo: x (Number) bar: y (Number) {
   # only executed if both argument patterns match.
}
```

**Comment by bakkdoor** [comment]
hmm this is kind of tedious, especially if you have several patterns for one method.. I'd prefer a clojure-style way of defining things, e.g.:

```
def foo: x bar: y
(Number, Number) -> {
  # in this case x and y are Numbers 
}
(String, Number) -> {
  # in this case x is a String, y a Number
}
```

or something like that.
What do you think?

**Comment by bakkdoor** [comment]
Another way would be to have a match keyword or so, which would allow you to do pattern matching basically anywhere, not just at the method-def layer.
e.g.

```
def foo: x bar: y {
  (x, y) match {
    (Number, Number) -> {
      # ...
    }
    (String, Number) -> {
      # ..
    }
  }
}
```

I personally like this better, since it's possible to do matching anywhere in the code and not just when defining methods.
Another benefit is, that this would simply compile down to several if-else constructs similar to ruby's case .. when ..

**Comment by vic** [comment]
Hm, I don't like clojure's approach, specially the fact that it doesn't make a big difference (to my eyes) from having a big case-clause, and you need to specify all patterns one after another. 
I prefer having them separate, even if that makes writing a little a more, the benefit is that code can be cleaner IMHO, having the possibility of defining each method on different files (as in ruby, we can re-open classes): 

   # foo.fy 

   def foo: x (Number) bar: (Number) {
      # work on numbers
   }

   # bar.fy

   def foo: x (String) bar: y (Number) {
       # an string and number
   }

Also with the approach I propose, specifying a pattern per argument, allows to match only on things you need, eg, have the first argument be anything and just match the second or third. 

```
 def foo: x bar: y baz: z (Number) {
     # x and y may be anything, but z is a Number for sure
 }
```

**Comment by vic** [comment]
You know .. 

We can have  

  (x, y) match {
    (Number, Number) -> {
      # ...
    }
    (String, Number) -> {
      # ..
    }
  }

to live side-by-side with what I propose, what you write is only how we would do case-pattern-matching. 

Actually, in the case of methods,

def foo: x (Number) bar: y (Number) {
   # only executed if both argument patterns match.
}

def foo: x (String) bar: y (Number) {
   # only executed if both argument patterns match.
}

Could compile to (internally that's how the foo:bar method would look like: )

def foo: x bar: y {
  (x, y) match {
    (Number, Number) -> {
      # ...
    }
    (String, Number) -> {
      # ..
    }
  }
}

**Comment by bakkdoor** [comment]
OK, that argument does make sense. I'd say we support both forms though, since you don't only want to match on arguments, but locals as well..
Also, I'm not quite sure if I like the idea of pattern matching method args on their types. This totally defeats the dynamic message sending idea (duck typing). But we should support it, since it can be handy. I personally think pattern matching makes more sense on things other than just an object's type.

Anyway, just as a side note, the main inspiration by erlang wasn't actually pattern matching but actors & asynchronous message sends, which we still have to implement ;)

**Comment by bakkdoor** [comment]
Right. I'd say we go for supporting both. Want to work on that?

**Comment by bakkdoor** [comment]
Yes, compiling your version to what I proposed makes more sense and also is easier to implement.
The compiler would basically collect all method def's that have the same name (keywords) into an array with the pattern's added to them and when compiling the method def, create a match expression from that or so. So I guess we'd have to implement the match syntax first, and can implement the method-def-matching on top of that, no?

**Comment by vic** [comment]
Yeah, got your point on using types, but that's only a particular case I used for examples, you can match on anything that supports ===, just used Number and String types to get an idea. 

So in fancy we will have "match" clause pattern-matching (I knew that from scala) and the particular case I propose for method_def will just compile internally to a big "match" clause.

**Comment by vic** [comment]
Yeah lets' do this.. 

Let's leave this issue for pattern-matching on method_def .. I'll open another one for the more general "match" clause.

**Comment by bakkdoor** [comment]
We need to change the syntax for this, since () is now used for default args. 
I'd suggest the following syntax:

```
def foo: x [Number] bar: y [Number] {
   # only executed if both argument patterns match.
} 
```

**Comment by bakkdoor** [comment]
Closing this for now since this most likely isn't going to be added anytime soon.
