### ISSUE TITLE
Pattern Matching - Match clause  (fancy's case statement)

### ISSUE THREAD

**Issue by vic** [bakkdoor/fancy#39]
So, after discussing pattern-matching-dispatch, here we have a more general case for pattern matching as an statement.

@bakkdoor's proposal is...

```
  (x, y) match {
    (Number, Number) -> {
      # ...
    }
    (String, Number) -> {
      # ..
    }
  }
```

That's very nice, and the syntax very similar to what we see in other langs (reminds me of scala)

I think we could use => instead of -> or .. maybe even remove that and use "block literals" to reuse parser rules.

```
  (x, y) match {
    |Number, Number| {
      # ...
    }
    |String, Number|  {
      # ..
    }
  }
```

Comments?

**Comment by bakkdoor** [comment]
I think I'd prefer not using block literals since this might make the parser more ambigious  and harder, since we'd like to support using block literals within a match clause, right? I'd prefer my original idea (the upper one) for that reason. It can't cause confusion.

**Comment by vic** [comment]
Yeah .. you're right ..

```
exp match {
   exp -> exp
}
```

**Comment by bakkdoor** [comment]
Right.

**Comment by bakkdoor** [comment]
Ok, got it working now. But I'm using == right now instead of ===. === Does't seem to work (at least not Ruby's version of that method). We can of course override it (and probably should) to make it be the "match operator". Comments?

**Comment by vic** [comment]
Done.
