### ISSUE TITLE
Create scope for match clause ?

### ISSUE THREAD

**Issue by NilsHaldenwang** [bakkdoor/fancy#47]
See this: http://github.com/bakkdoor/fancy/commit/5e4f6c81426ff9f8d9b066b78edcd0a8d56cd504

The match arg should only be in scope of match clause or not ? Actually there is no scope for this I guess.

Not sure how to do this, that's why I'm just writing the Issue. :P

What do you think ?

**Comment by bakkdoor** [comment]
Good point, will fix.

**Comment by bakkdoor** [comment]
If matcharg is given to case's body, only make it visible within the body, not afterwards (outside of it). Closed by 357fda2c1f8b3b951f6495d7b4d0d38d08c96744
