### ISSUE TITLE
Rename fancydoc/fdoc ?

### ISSUE THREAD

**Issue by bakkdoor** [bakkdoor/fancy#48]
Hey, I just got this fun idea =)

Right now we have `fdoc`, written by vic, and `fancydoc` in bin/.
The former generates an html page with documentation. The latter is an old script I had written that displays documentation information on the console, much like the `ri` command for Ruby. It's currently not working on rbx, but that should not be too hard to fix (we basically need String#eval to return the value of the eval I think).

So my idea is to rename either `fdoc` or `fancydoc` to `fyi`. I currently think renaming `fancydoc` makes more sense and let `fdoc` continue to have the same name. "FYI" is the english abbreviation for "For Your Information", which makes sense as a name for a tool that gives command-line information on methods & classes, like Ruby's `ri` command =). Also, it includes Fancy's "fy" file extension so it could also be read as "Fancy Information" or whatever.

What do you think?

**Comment by bakkdoor** [comment]
So the idea is to use `fyi` in the following way:

```
$ fyi Array#[]
```

This would print something like:

```
Documentation for: Array#[]:
Given an Array of 2 Numbers, it returns the sub-array between the
given indices.
If given a Number, returns the element at that index.
```

Maybe also display some code from the tests for that method, where it's defined, etc.

**Comment by NilsHaldenwang** [comment]
Yeah, I like this idea, rename the fancydoc to fyi and keep fdoc as fdoc.

**Comment by bakkdoor** [comment]
Yup done so already :P

**Comment by goyox86** [comment]
I like fyi :)
