### ISSUE TITLE
Implement lazy argument evaluation - Macros.

### ISSUE THREAD

**Issue by vic** [bakkdoor/fancy#49]
It would be really nice to have methods in fancy that don't evaluate their arguments unless explicitly done so. This kind of methods (commonly named macros) can be used to manipulate fancy code and produce other code. 

 Syntax proposal: 

```
 macro foo: bar {
   # bar is not evaled, unless we explicity make it to.
   # there's the possibility of inspecting, and modifing the code bar represents.
   bar eval_at: caller context
 }
```

I'm proposing using a new "macro" keyword instead of "def" .. or maybe "defm" (read as define macro) .. or that could be 

```
def macro foo: bar { ... }
```

**Comment by bakkdoor** [comment]
Looks good. I personally like "def macro".

**Comment by bakkdoor** [comment]
We should probably also allow compile-time macros as well. This allows faster execution during runtime. Maybe make a distinction via:
    def macro foo: bar { .. }
for compile-time macros and
    def lazy foo: bar { ... }
for runtime "macros" (lazy evaluating methods).

For compile-time macros, we'd need support for "unquoting" (inserting) the arguments' value in the macro's body. I suggest using a lisp-like syntax for this:

```
def macro 10times: bar {
    # "~" unquotes an expression behind it. in this case a literal block, which means
    # the block's body gets executed during compile-time and anything preceded
    # with a "`" is quoted (part of the generated code). 
    # the ~@ injects the results of the body followed by it as an expression list.
    # so if this macro is called with: 10times: { "foo" println }
    # it should generate the following code: 
    # "foo" println; "foo" println; "foo" println; "foo" println; "foo" println; "foo" println; "foo" println; "foo" println; "foo" println; "foo" println; 
    # the implementation could look something like this:
     `{
         ~@{ 10 times: { `~bar } }
      }
}
```

**Comment by bakkdoor** [comment]
Not gonna add this any time soon. Closing for now.
