### ISSUE TITLE
Fancy Package system

### ISSUE THREAD

**Issue by bakkdoor** [bakkdoor/fancy#50]
I started working on a simple package system for fancy.
The idea is to install packages via
    $ fancy install bakkdoor/mongo.fy
which will install the latest version of http://github.com/bakkdoor/mongo.fy

So fancy's package system will rely on git for all the versioning stuff etc. As a default we'll use Github for now. You should also be able to specify a version, e.g.
    $ fancy install bakkdoor/mongo.fy=v0.1.2

Each package will need to have a .fancypack file, e.g. mongo.fy.fancypack. When a package (a git repo) is downloaded, it will look into its root directory and search for a .fancypack file and run it to get its dependencies and download those etc. (similar to rubygems)
This is a work-in-progress. Help / Ideas appreciated.

**Comment by krainboltgreene** [comment]
Schema-less specs: If you have to deprecate the 'author' field (for say, 'authors') you wont have to worry about API deprecation because the specs are schema-less. (Big issue for me with Ruby gemspecs)

**Comment by bakkdoor** [comment]
Not sure if I understand you correctly. Could you elaborate a bit? How exactly would you want it to work?

**Comment by krainboltgreene** [comment]
Meaning if I don't include the "author" field, or the "homepage" field, it shouldn't fail. A gemspec build fails if you don't include specific fields, or if you try to use your own fields.

**Comment by bakkdoor** [comment]
Closing this. I'll probably add schema-less specs.
