### ISSUE TITLE
Bug with if_do:else: on a single line.

### ISSUE THREAD

**Issue by vic** [bakkdoor/fancy#52]
From IRC:

```
   <vborja> this should print "Works"
   <vborja> ! "something" match(r{me}) . if_do: { "Works" } else: { "Nasty bug" } . println
   <fancy_bot> =>
   <vborja> ! s = "nasty" == "bug" . if_do: { "Fix" } else: { "Me" } ; s println
   <fancy_bot> => Fix
```

Dunno if this is a problem in the compiler or parser , but I guess so, we need to investigate.

**Comment by bakkdoor** [comment]
The first one doesnt display anything because it's a syntax error. match syntax looks like this:

```
match obj -> {
  case -> ...
  ...
}
```

**Comment by bakkdoor** [comment]
The second doesn't work as expected because if_do: is implemented to check only for nil?
Need to fix that.

**Comment by vic** [comment]
hmm.. not using pattern-matching , but calling the _match_ method on ruby strings.  that should be possible, imho.

**Comment by bakkdoor** [comment]
Ah ok,sorry got it. I guess it's a precedence problem.. Dunno

**Comment by bakkdoor** [comment]
Tried it again is fixed now.
