### ISSUE TITLE
Fancy Literate Programming.

### ISSUE THREAD

**Issue by vic** [bakkdoor/fancy#54]
We have docstring to be simply string literals, that's really cool, as we could implement literate programming documentation like http://rtomayko.github.com/rocco/  by simply using the expressions that are nothing but otherwise-non-used string-literals.

```
  def  foo {
       " The first string is the method documentation"

        ary = obtain_array

        "But we could allow other string literals to be used for literate programming."
        ary some: stuff

        "And we could use this  to display side-by-side documentation-to-code as rocco does."
        ary join("\n")
  }
```

The idea is to display this at fdoc/index.html in the documentation for the method. 

So for example, we'll basically end with the following _html_ structure on fdoc:

```
     <method_name_and_args>                            <gh_link>
     <*tab1: literate source code>  | <tab2: usage example> | <tab3: related specs>

      Method Documentation. ie. the first non-used string literal.
      @return | Doclets annotations.

      [toggle] 
      Explaining what the folloing     |
      code does, side by side          |     Some Fancy code: here
      These strings were extracted     |     described by: sidebar
      From the source, and this        |     each: String literal $ used as: docs
      can be toggled off/on.           |     Code is: pygmentized.
```

The toggle control will allow you to show the method body in three modes: "only source code", "side-by-side literate-doc <-> source code" or just "literate docs"  explaining the method implementation.

**Comment by bakkdoor** [comment]
This Sounds awesome! We should Do it :-)

**Comment by goyox86** [comment]
Sounds good, i think we sholud establish some conventions on the use of this feature,IMHO, since we could end with more comments than code. :)

**Comment by vic** [comment]
goyox86, sure actually this feature shouldn't be abused, as I believe fancy code should be as communicate as possible by itself. So we should use literate programing only for documenting implementation details, like why you choose certain algorithm or the like, I believe this is something missing on other languages, most of the time you have documented apis, but not documented implementations, so we should make the convention to document only not-so-evident software design, problems or limitations of a certain implementation, and not for documenting every line ;).

**Comment by bakkdoor** [comment]
Closing this for now. We can get back to this if we want to anytime.
