### ISSUE TITLE
Different rbx bytecode output between boot/rbx-compiler/ and lib/compiler

### ISSUE THREAD

**Issue by bakkdoor** [bakkdoor/fancy#58]
Here's a gist showing just the difference for compiler/ast/message_send.fyc:

https://gist.github.com/711690

I think this was causing the problems with the bootstraping process we had. Apparently the fancy-written compiler is emitting different bytecode than the original bootstrap compiler. We need to fix this.

**Comment by vic** [comment]
We used the "diff"  branch for inspecting differences between the ruby-compiler and the fancy one. Later bakkdoor and brixen discovered that the bug we were having was an issue with Rubinius JIT. So I'm closing this ticket.
