### ISSUE TITLE
Confused with parsing "/" operator

### ISSUE THREAD

**Issue by bakkdoor** [bakkdoor/fancy#64]
As @manveru noticed, this will fail to parse:

```
def / x { 
   '/
 }
```

But this will parse:

```
def / x {
  'foo
}
```

It looks like it's trying to parse it as a Regexp..

**Comment by vic** [comment]
Is this still the case? If so, I might be looking into fixing it.

**Comment by bakkdoor** [comment]
Just tried this in the repl, and got this:

> > def / x { '/ }
> > Error trying to compile (fancy-eval)

So yeah, looks like it. Go ahead if you want to fix this, that would be great. Totally forgot about this -_-

**Comment by bakkdoor** [comment]
Hey thanks! I was on a holiday trip so I just saw this. :) :+1:

**Comment by vic** [comment]
hehe :) no prob
