### ISSUE TITLE
cannot compile fancy

### ISSUE THREAD

**Issue by yawnt** [bakkdoor/fancy#70]
i'm getting this output on rubinius 2.0.0-rc1 while running `rake` after a git clone

```
Could not open library /Users/yawnt/Codes/fancy/lib/parser/ext/fancy_parser.bundle - dlopen(/Users/yawnt/Codes/fancy/lib/parser/ext/fancy_parser.bundle, 10): Symbol not found: _yywrap (LoadError::InvalidExtensionError)
```

**Comment by vic** [comment]
Could you run rake clean and then rake again and create a gist of the output. Are you missing flex or bison on your LD_LIBRARY_PATH?

**Comment by yawnt** [comment]
i had to `ln -s` a library because OSX uses another name... after `rake clean && rake` it worked perfectly.. thank you

**Comment by vic** [comment]
Ok, glad to know things worked out.

**Comment by jbancroft** [comment]
@yawnt Do you by any chance remember which library you needed to link and which version of OSX you were using? I think I am running into the same problem and although I'm sure I'll track down the solution eventually, if you already know the answer and can help me out, I'd surely appreciate it :-)

**Comment by bakkdoor** [comment]
@jbancroft Check out this irc log: http://irc.fancy-lang.org/logs/2013-07/%23fancy_2013-07-05.txt 
Looks like you have to rename libl to libfl? Hope this helps, if not, let us know.

**Comment by jbancroft** [comment]
Oh yea my bad. I actually did end up solving this. Basically there's something in the build process that looks for `/usr/lib/libfl.a` which doesn't exist on recent versions of OSX. However, `/usr/lib/libl.a` provides similar enough functionality that you can just `ln -s /usr/lib/libfl.a /usr/lib/libl.a` and then it works!

**Comment by bakkdoor** [comment]
cool, good to hear you got it working.
